### ISSUE TITLE
Input data normalization

### ISSUE THREAD

**Issue by carriojazz** [harvitronix/reinforcement-learning-car#14]
Hey Matt, I've seen that you don't normalize the sensor readings before feeding them to the network. Are you not normalizing for some reason? Also I wonder how does the LSTM perform, could you give any feedback?

**Comment by harvitronix** [comment]
Thanks for the PR!

As for the LSTM, I didn't spend much time on it so don't recall how it performed. Would be fun to pick that back up, though. I imagine it would do well.
