### ISSUE TITLE
pymunk.body.apply_impulse

### ISSUE THREAD

**Issue by kargarisaac** [harvitronix/reinforcement-learning-car#17]
When I run the learning.py file, it gives me the " AttributeError: 'Body' object has no attribute 'apply_impulse'" error. which version of pymunk used in the code. how can I fix the problem?

**Comment by harvitronix** [comment]
This is due to using Pymunk >= 5.

Unfortunately when I wrote this code, Pymunk 4 was the latest, and there were significant changes going to 5.

Quick way to downgrade is:
`pip3 install pymunk==4.0.0`

Then CD into your dist-packages/pymunk and run `2to3 -w *py`.

This fixed it for me recently.
