### ISSUE TITLE
Run for first time - detail request

### ISSUE THREAD

**Issue by MrZantag** [harvitronix/reinforcement-learning-car#6]
Hi Matt, 

What you have been able to do with this project is amazing! I would like to get this program running on my system but after working at if for 3 days nothing seems to work when it comes to environment set up. I was hoping you could add more detail on how you set up your environment on the readme.

What did you start with as your "base"? Was it purely python or did you start with something like Anaconda?

Also when I was recently trying to install pymunk 4.0.0 I got errors with Chipmunk and was wondering if you had any similar issues when you set up your environment. 

Thanks,
MrZantag

P.S. If there is a better spot to post these questions please let me know!

**Comment by llSourcell** [comment]
@harvitronix yea i'm about to post a video about this code, please do tell

**Comment by harvitronix** [comment]
Hey guys. Really sorry for my delay! I'll put up more detail later today. Cheers!

**Comment by harvitronix** [comment]
@MrZantag To answer your base question: I'm on OS X and installed standard Python 3 with Brew. Then did the same with pip3. So I didn't start with anything like anaconda.

I seem to recall getting errors with Chipmunk as well but it's been a while. I won't have time to do this today, but I will do my best to spin up a VM tomorrow, start the installation from scratch and write a better step-by-step guide. I know you aren't the only one running into the setup's quirks.

**Comment by harvitronix** [comment]
@MrZantag @llSourcell

I'll update the readme when I have more time. In the meantime, I've managed to get it running from scratch in Ubuntu 16.04 with the following sequence of events:

Install python3 (already on new ubuntu)
Install pip3 with `sudo apt install python3-pip`
Install git with `sudo apt install git`

Clone this repo with `git clone https://github.com/harvitronix/reinforcement-learning-car.git` (add —depth 1 for faster download)
CD into the repo with `cd reinforcement-learning-car`

Install the dependencies:
`pip3 install numpy keras h5py`

pygame
`sudo apt install mercurial libfreetype6-dev libsdl-dev libsdl-image1.2-dev libsdl-ttf2.0-dev libsmpeg-dev libportmidi-dev libavformat-dev libsdl-mixer1.2-dev libswscale-dev libjpeg-dev`
`pip3 install hg+http://bitbucket.org/pygame/pygame`

pymunk
`cd back to your ~`
donload pymunk 4: `wget https://github.com/viblo/pymunk/archive/pymunk-4.0.0.tar.gz`
unpack: `tar zxvf pymunk-4.0.0.tar.gz`
`cd pymunk-pymukn-4.0.0`
`cd pymunk`
`2to3 -w *.py`
`cd ..`
`python3 setup.py install`

run!
`python3 learning.py`

Note: you may need to add `sudo` to all the pip3 commands.

**Comment by harvitronix** [comment]
[Readme](https://github.com/harvitronix/reinforcement-learning-car/blob/master/README.md) updated with more details.
