### ISSUE TITLE
Error while installing keras in open suse

### ISSUE THREAD

**Issue by Amaravati** [harvitronix/reinforcement-learning-car#7]
Hi, 
     I did install python3 and got the repository using git. While installing kera using: pip3 install numpy keras h5py, am facing error. I have attached snapshot. I want to install the ubuntu box and give a try.. If you can provide me the link for ubuntu box version dvd it would be helpful.

![python_install](https://cloud.githubusercontent.com/assets/10122691/21792790/368a3c66-d6ba-11e6-8859-1aa455a1abbe.PNG)

**Comment by srnand** [comment]
The problem is in h5py.
You need to install libhdf5-dev to get the required header files. Just run
sudo apt-get install libhdf5-dev
and it should install it and its dependencies automatically.
Then go with your command.
