### ISSUE TITLE
Error importing draw from pymunk.pygame_util

### ISSUE THREAD

**Issue by mzkhan141** [harvitronix/reinforcement-learning-car#8]
I wanted to run your code on my window 10 with 32bit python installed but its giving me an ImportError saying cannot import name draw  which is occurring on carmunk.py file please help

**Comment by Vlad1094** [comment]
Hello @mzkhan141 change it to pymunk.pygame_util.DrawOptions

**Comment by mzkhan141** [comment]
now it says no module named DrawOptions

**Comment by anthdm** [comment]
This will do the trick.

from pymunk.pygame_util import DrawOptions as draw

**Comment by anthdm** [comment]
You will get more issues with version > 5.0.0 from pymunk. Solution is pip install pymunk == 4.0.0

**Comment by harvitronix** [comment]
As @anthdm said, you need to use pymunk 4.

Quick way to downgrade is:
`pip3 install pymunk==4.0.0`

Then CD into your dist-packages/pymunk and run `2to3 -w *py`.

This fixed it for me recently.

**Comment by Sandy4321** [comment]
from pymunk.pygame_util import DrawOptions as draw 
works thanks
but
game_state = carmunk.GameState()
gives error
builtins.NameError: name 'carmunk' is not defined
