### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'python'

### ISSUE THREAD

**Issue by firatbey** [harvitronix/reinforcement-learning-car#9]
Hi, I get the following error when I execute python3 learning.py

Loading chipmunk for Linux (64bit) [/usr/local/lib/python3.5/dist-packages/pymunk/libchipmunk64.so]
Using TensorFlow backend.
Traceback (most recent call last):
  File "learning.py", line 5, in <module>
    from nn import neural_net, LossHistory
  File "/home/kiwis/reinforcement-learning-car/nn.py", line 15, in <module>
    tf.python.control_flow_ops = tf
AttributeError: module 'tensorflow' has no attribute 'python'

I am relatively new to python, your help would be greatly appreciated

**Comment by harvitronix** [comment]
@firatbey Looks like you may have an older version of TensorFlow. What version are you on?

**Comment by ahtsan** [comment]
I have the same problem
my tensorflow version is 
tensorflow-1.0.1-cp35-cp35m-manylinux1_x86_64

**Comment by ahtsan** [comment]
I am in ubuntu 16.04, fresh install

**Comment by ahtsan** [comment]
I was able to get it running for around 2 seconds, and then it pops up 
"AttributeError: module 'tensorflow' has not attribute 'global_variables'"
What is your tensorflow version? I am using 0.10.0

**Comment by ahtsan** [comment]
Finally I got it running by installing the 1.0.0 tensorflow.

Another question: can I get a pre-trained nn file instead of training myself?

**Comment by ahtsan** [comment]
Because I am using ubuntu on a mac, and the training becomes very slow after several seconds, fps drops from 4xx to around10.

**Comment by Aziiz1989** [comment]
I am on windows 10, I used I changed keras backend settings to theano instead of tensorflow and it works

**Comment by Microos** [comment]
I just removed that statement and things still work well.

**Comment by harvitronix** [comment]
Fixed in #18
